export const MARBLE_PRODUCTS = [
  {
    name: "Calacatta Gold",
    type: "white",
    finish: "polished",
    description: "Luxurious white marble with gold veining",
  },
  {
    name: "Statuario Venato",
    type: "white",
    finish: "polished",
    description: "Classic white with gray veins",
  },
  {
    name: "Nero Marquina",
    type: "black",
    finish: "polished",
    description: "Deep black with white veins",
  },
  {
    name: "Emperador Dark",
    type: "brown",
    finish: "polished",
    description: "Rich brown with light veins",
  },
  {
    name: "Carrara White",
    type: "white",
    finish: "honed",
    description: "Timeless Italian white marble",
  },
  {
    name: "Verde Guatemala",
    type: "green",
    finish: "polished",
    description: "Exotic green marble",
  },
  {
    name: "Crema Marfil",
    type: "beige",
    finish: "polished",
    description: "Warm beige tones",
  },
  {
    name: "Portoro Gold",
    type: "black",
    finish: "polished",
    description: "Black with golden veins",
  },
  {
    name: "Rosa Portuges",
    type: "pink",
    finish: "polished",
    description: "Elegant pink marble",
  },
  {
    name: "Bianco Sivec",
    type: "white",
    finish: "polished",
    description: "Pure white crystalline",
  },
  {
    name: "Blue Sodalite",
    type: "blue",
    finish: "polished",
    description: "Rare deep blue marble",
  },
  {
    name: "Breccia Oniciata",
    type: "multi",
    finish: "polished",
    description: "Multi-colored breccia",
  },
  {
    name: "Calacatta Borghini",
    type: "white",
    finish: "polished",
    description: "Premium white with dramatic veins",
  },
  {
    name: "Thassos White",
    type: "white",
    finish: "polished",
    description: "Purest white Greek marble",
  },
  {
    name: "Rosso Levanto",
    type: "red",
    finish: "polished",
    description: "Rich red with white veins",
  },
  {
    name: "Arabescato",
    type: "white",
    finish: "polished",
    description: "White with arabesque patterns",
  },
  {
    name: "Travertino Romano",
    type: "beige",
    finish: "honed",
    description: "Classic Roman travertine",
  },
  {
    name: "Onyx Fantastico",
    type: "multi",
    finish: "polished",
    description: "Translucent onyx beauty",
  },
  {
    name: "Pietra Grey",
    type: "gray",
    finish: "honed",
    description: "Sophisticated gray limestone",
  },
  {
    name: "Calacatta Vagli",
    type: "white",
    finish: "polished",
    description: "Rare white with bold veining",
  },
  {
    name: "Black Galaxy",
    type: "black",
    finish: "polished",
    description: "Black granite with gold flecks",
  },
  {
    name: "Golden Spider",
    type: "beige",
    finish: "polished",
    description: "Beige with spider-web veins",
  },
  {
    name: "Azul Macaubas",
    type: "blue",
    finish: "polished",
    description: "Stunning blue quartzite",
  },
  {
    name: "White Princess",
    type: "white",
    finish: "polished",
    description: "Delicate white with gray",
  },
  {
    name: "Emperador Light",
    type: "brown",
    finish: "polished",
    description: "Light brown elegance",
  },
  {
    name: "Verde Alpi",
    type: "green",
    finish: "polished",
    description: "Alpine green serpentine",
  },
  {
    name: "Calacatta Monet",
    type: "white",
    finish: "polished",
    description: "Artistic white marble",
  },
  {
    name: "Fusion Wow",
    type: "multi",
    finish: "polished",
    description: "Dramatic multi-color quartzite",
  },
  {
    name: "Bianco Lasa",
    type: "white",
    finish: "polished",
    description: "Premium Italian white",
  },
  {
    name: "Portofino Limestone",
    type: "beige",
    finish: "honed",
    description: "Coastal beige limestone",
  },
];
